### PR TITLE
feat: add serinus framework benchmarks

### PR DESCRIPTION
**Pull request by francescovallone**
Hello, I tried to add my framework to the web framework list for Dart.

Let me know if there is any error and if I need to fix something before this PR can be accepted.

Thank you so much for your time!

### CODE REVIEW

**Comment by Tienisto** [comment]
Somehow I get timeouts. After stopping the server, I get

```json
{
	"message": "Route spec not found for route /api/v1/periodic-table/element",
	"statusCode": 500,
	"uri": "No Uri"
}
```

**Comment by Tienisto** [comment]
I believe there is a bug in your routing implementation. I added a workaround for now

**Comment by francescovallone** [comment]
Yes, sorry, I was solving the routing problem to complete the PR using version 0.3.1 because it is more performant than 0.3.

For the routing bug, yes it seems to be an error with the route normalisation function, I'll prioritise fixing it as it's quite serious. Thanks anyway for finding a workaround, if it's OK with you I'll do another PR when I've solved the problem with the router.

**Comment by Tienisto** [comment]
Sure, no problem

**Pull request merged**
