### PR TITLE
Add Laravel 11.10.0

### PR DESCRIPTION
**Pull request by javad-zobeidi**

### CODE REVIEW

**Comment by Tienisto** [comment]
Thank you! Can we make it simpler (e.g. by removing the tests)?

**Comment by javad-zobeidi** [comment]
@Tienisto  Yes

**Comment by Tienisto** [comment]
The `/api/v1/periodic-table/shells` route must return 

```json
{
	"shells": [
		2
	]
}
```

but it currently returns

```json
[
	2
]
```

**Comment by Tienisto** [comment]
Hi, thanks for your fix. Why did you closed the PR?

**Pull request closed without merging**
